### ISSUE TITLE
Pagina di snodo per scelta Comune al voto

### ISSUE THREAD

**Issue by filipic** [openpolis/voisietequi#21]
All'indirizzo www.voisietequi.it dovrà rispondere una pagina di snodo con la scelta del Comune al voto.
Gli elementi in pagina saranno quindi:
- [x] bottoni per la scelta del comune (Roma, Milano, Napoli, Torino)
- [ ] counter generale di quanti utenti hanno fatto il test
- [x] invito alla donazione e al 5x1000.

In allegato, solo per maggiore chiarezza, lo screenshot della pagina di snodo utilizzata nel 2012.

<img width="1268" alt="schermata 2016-05-02 alle 12 52 20" src="https://cloud.githubusercontent.com/assets/1142860/14952881/cab3cdde-1064-11e6-9b53-95beb752b392.png">

**Comment by filipic** [comment]
I layout da montare sta qui:
http://www.d3s1gn.it/progetti/voisietequi/hp.html
in questa fase nascondere "XXX cittadini conoscono già la propria posizione"

**Comment by joke2k** [comment]
@rob3rto puoi darmi le immagini del dona e del 5xmille in png con sfondo trasparente?

**Comment by rob3rto** [comment]
![5x1000](https://cloud.githubusercontent.com/assets/19184879/15293168/050548fa-1b87-11e6-945e-b4b453f685d6.png)
![dona](https://cloud.githubusercontent.com/assets/19184879/15293169/0539a032-1b87-11e6-84b9-75d6e3f56fdb.png)

**Comment by rob3rto** [comment]
![5x1000](https://cloud.githubusercontent.com/assets/19184879/15293248/70b19054-1b87-11e6-9df6-b4d7d16b1574.png)
![dona](https://cloud.githubusercontent.com/assets/19184879/15293249/70e9a872-1b87-11e6-921b-575e368c1ae6.png)

**Comment by joke2k** [comment]
grazie
