### ISSUE TITLE
Cambiare sfondo nel grafico delle distanze

### ISSUE THREAD

**Issue by filipic** [openpolis/voisietequi#24]
Cambiare lo sfondo al grafico delle distanze con le stesse dimensioni. Quello attuale è questo:

http://europee2014.voisietequi.it/static/img/grafico/bg_liste.png

**Comment by rob3rto** [comment]
![bg_liste](https://cloud.githubusercontent.com/assets/19184879/15293527/af06a596-1b88-11e6-91d6-02b6bd315e43.png)

**Comment by rob3rto** [comment]
![bg_liste](https://cloud.githubusercontent.com/assets/19184879/15293764/d7c8e60a-1b89-11e6-8ce9-f653d1179acf.png)
