### ISSUE TITLE
Condividi social nella pagina del risultato

### ISSUE THREAD

**Issue by filipic** [openpolis/voisietequi#27]
- [x] Twitter e facebook: "Ecco la distanza fra me e i candidati a [nome_comune]. Tu dove sei? #vsq2016 #[nome_comune]2016 #amministrative2016 http://roma2016.voisietequi.it/risultato/9025e7003f676c5234e2787dad11fe2c/"
- [x] vedere se si riesce, per tw e fb, a inserire l'immagine del grafico

**Comment by joke2k** [comment]
La frase è molto lunga, dobbiamo fare dei test su una delle istanze tra Milano/Torino/Napoli per vedere se non sfora i caratteri di twitter. Su facebook invece ho impostato i meta di opengraph e dovrebbe funzionare. (da provare live)

La condivisione dell'immagine su twitter non si può fare tramite addthis (strumento che ci condivide la roba), mentre per facebook dovrei aver risolto ma per testarlo devo fare una prova live. (il crowler di facebook non funziona in locale)
