### ISSUE TITLE
Meccanismo per tenere offline il frontend fino alla data di inizio

### ISSUE THREAD

**Issue by guglielmo** [openpolis/voisietequi#28]
Mentre il backend deve essere online, per poter inserire domande, faq, e candidati, e permettere ai candidati di rispondere al questionario, il frontend deve essere spento.

Avevamo già implementato un meccanismo del genere?

**Comment by joke2k** [comment]
Si c'era l'EARLYBIRD da abilitare attraverso i settings e il .env.
Un meccanismo un po rudimentale ma funziono'.
L'unica rottura sarebbe replicarlo per le 4 istanze...
