### ISSUE TITLE
Feed Notizie per singola istanza

### ISSUE THREAD

**Issue by filipic** [openpolis/voisietequi#37]
Nelle home delle singole istanze va preso il feed di notizie specifico per il singolo comune.

Gli indirizzi dei feed sono:

- http://blog.openpolis.it/categorie/piattaforme/voisietequi/roma2016/feed
- http://blog.openpolis.it/categorie/piattaforme/voisietequi/milano2016/feed
- http://blog.openpolis.it/categorie/piattaforme/voisietequi/torino2016/feed
. http://blog.openpolis.it/categorie/piattaforme/voisietequi/napoli2016/feed

**Comment by joke2k** [comment]
E' sufficiente impostare 
OP_BLOG_CATEGORY=piattaforme/voisietequi/roma2016
OP_BLOG_CATEGORY=piattaforme/voisietequi/milano2016
OP_BLOG_CATEGORY=piattaforme/voisietequi/torino2016
OP_BLOG_CATEGORY=piattaforme/voisietequi/napoli2016
nel file .env
