### ISSUE TITLE
Foto candidati con aggiunta di nome/cognome

### ISSUE THREAD

**Issue by filipic** [openpolis/voisietequi#38]
Nella home page, nella pagina http://roma2016.voisietequi.it/liste/  dove c'è la foto del candidato bisogna aggiungere anche il nome e cognome come in questo layout:

![hp_roma](https://cloud.githubusercontent.com/assets/1142860/15428117/d667870e-1e99-11e6-903e-1486e7d219a2.png)

**Comment by joke2k** [comment]
Nella home ci entrerebbero pure,
ma nella pagina delle liste non c'è tanto spazio.
L'ho provato con i dati delle europee... "Nuovo Centrodestra - Unione Dei Demoratici Cristiani e Democratici Di  Centro" sfasa un po tutto. Potrei metterci la sigla... che ne dici? (attualmente è il cognome del candidato maiuscolo)

**Comment by joke2k** [comment]
Comportamento responsive

**Comment by filipic** [comment]
metti i nomi in nero e non in rosso
